// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCut1f5ZrhVb_SJxdsKuaaJ_07hSPNQjg0',
    appId: '1:747297361068:web:d36ae56d4da6c9d2992309',
    messagingSenderId: '747297361068',
    projectId: 'code-path-dd2c0',
    authDomain: 'code-path-dd2c0.firebaseapp.com',
    storageBucket: 'code-path-dd2c0.firebasestorage.app',
    measurementId: 'G-56W8CHJL4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwv29xcwJ6nuChWXrDh1IBWHTADFXlq8w',
    appId: '1:747297361068:android:4a1c68f1104624da992309',
    messagingSenderId: '747297361068',
    projectId: 'code-path-dd2c0',
    storageBucket: 'code-path-dd2c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJTHsMXhHbHXnK5T1jqJVxqysCm2c0iTQ',
    appId: '1:747297361068:ios:4a98670f9402aabd992309',
    messagingSenderId: '747297361068',
    projectId: 'code-path-dd2c0',
    storageBucket: 'code-path-dd2c0.firebasestorage.app',
    iosBundleId: 'com.example.codePath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJTHsMXhHbHXnK5T1jqJVxqysCm2c0iTQ',
    appId: '1:747297361068:ios:4a98670f9402aabd992309',
    messagingSenderId: '747297361068',
    projectId: 'code-path-dd2c0',
    storageBucket: 'code-path-dd2c0.firebasestorage.app',
    iosBundleId: 'com.example.codePath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCut1f5ZrhVb_SJxdsKuaaJ_07hSPNQjg0',
    appId: '1:747297361068:web:f725885f439821a3992309',
    messagingSenderId: '747297361068',
    projectId: 'code-path-dd2c0',
    authDomain: 'code-path-dd2c0.firebaseapp.com',
    storageBucket: 'code-path-dd2c0.firebasestorage.app',
    measurementId: 'G-Q8N6ZW8X1W',
  );
}
